TARGET_FILE_NAME = 'lista_alvo.csv'

INPUT_COLUMNS = ['LATITUDE', 'LONGITUDE', 'PONTO DE GRADE Y',
                 'PONTO DE GRADE X', 'VALOR DA SIMULACAO', 'VALOR DE OBSERVACAO',
                   'DIA', 'MES', 'ANO']

TARGET_COLUMN = 'ALVO'

GROUP_BY_COLUMN = 'ANO'